name = "vincertbot"
main = "src/index.js"
compatibility_date = "2024-05-31"
workers_dev = true

# All sensitive variables (BOT_TOKEN, AUTORIA_API_KEY, AUTORIA_USER_ID, BAZAGAI_API_KEY)
# are stored securely using Cloudflare Secrets. Do not add them here.
